/*
 *
 * User actions types.
 *
 */
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_USER_BY_USERNAME = 'FETCH_USER_BY_USERNAME';
export const FETCH_ALL_USER_REPOS = 'FETCH_ALL_USER_REPOS';
export const CLEAR_FETCHED_USER = 'CLEAR_FETCHED_USER';
export const CLEAR_FETCHED_USER_REPOS = 'CLEAR_FETCHED_USER_REPOS';


